const std::map<std::string, std::string> cp15_ops = {
    {"mrc p15 0 <Rd> c0 c0 0", "Read ID Code Register"},
    {"mrc p15 0 <Rd> c0 c0 1", "Read Cache Type Register"},
    {"mrc p15 0 <Rd> c0 c0 3", "Read TLB Type Register"},
    {"mrc p15 0 <Rd> c0 c0 5", "Read CPU ID Register"},
    {"mrc p15 0 <Rd> c0 c0 0", "Read Proc Feature Register 0"},
    {"mrc p15 0 <Rd> c0 c1 1", "Read Proc Feature Register 1"},
    {"mrc p15 0 <Rd> c0 c1 2", "Read Debug Feature Register 0"},
    {"mrc p15 0 <Rd> c0 c1 4", "Read Memory Feature Register 0"},
    {"mrc p15 0 <Rd> c0 c1 5", "Read Memory Feature Register 1"},
    {"mrc p15 0 <Rd> c0 c1 6", "Read Memory Feature Register 2"},
    {"mrc p15 0 <Rd> c0 c1 7", "Read Memory Feature Register 3"},
    {"mrc p15 0 <Rd> c0 c2 0", "Read ISA Feature Register 0"},
    {"mrc p15 0 <Rd> c0 c2 1", "Read ISA Feature Register 1"},
    {"mrc p15 0 <Rd> c0 c2 2", "Read ISA Feature Register 2"},
    {"mrc p15 0 <Rd> c0 c2 3", "Read ISA Feature Register 3"},
    {"mrc p15 0 <Rd> c0 c2 4", "Read ISA Feature Register 4"},

    {"mrc p15 0 <Rd> c1 c0 0", "Read Control Register"},
    {"mcr p15 0 <Rd> c1 c0 0", "Write Control Register"},
    {"mrc p15 0 <Rd> c1 c0 1", "Read Auxiliary Control Register"},
    {"mcr p15 0 <Rd> c1 c0 1", "Write Auxiliary Control Register"},
    {"mrc p15 0 <Rd> c1 c0 2", "Read Coprocessor Access Control Register"},
    {"mcr p15 0 <Rd> c1 c0 2", "Write Coprocessor Access Control Register"},

    {"mrc p15 0 <Rd> c2 c0 0", "Read Translation Table Base Register 0"},
    {"mcr p15 0 <Rd> c2 c0 0", "Write Translation Table Base Register 0"},
    {"mrc p15 0 <Rd> c2 c0 1", "Read Translation Table Base Register 1"},
    {"mcr p15 0 <Rd> c2 c0 1", "Write Translation Table Base Register 1"},
    {"mrc p15 0 <Rd> c2 c0 2", "Read Translation Table Base Control Register"},
    {"mcr p15 0 <Rd> c2 c0 2", "Write Translation Table Base Control Register"},

    {"mrc p15 0 <Rd> c3 c0 0", "Read Domain Access Control Register"},
    {"mcr p15 0 <Rd> c3 c0 0", "Write Domain Access Control Register"},

    {"mrc p15 0 <Rd> c5 c0 0", "Read Data Fault Status Register"},
    {"mcr p15 0 <Rd> c5 c0 0", "Write Data Fault Status Register"},
    {"mrc p15 0 <Rd> c5 c0 1", "Read Instruction Fault Status Register"},
    {"mcr p15 0 <Rd> c5 c0 1", "Write Instruction Fault Status Register"},

    {"mrc p15 0 <Rd> c6 c0 0", "Read Fault Address Register"},
    {"mcr p15 0 <Rd> c6 c0 0", "Write Fault Address Register"},
    {"mrc p15 0 <Rd> c6 c0 1", "Read Watchpoint Fault Address Register"},
    {"mcr p15 0 <Rd> c6 c0 1", "Write Watchpoint Fault Address Register"},

    {"mcr p15 0 <Rd> c7 c0 4", "Wait For Interrupt"},
    {"mrc p15 0 <Rd> c7 c4 0", "PA Register"},
    {"mcr p15 0 <Rd> c7 c5 0", "Invalidate Entire Instruction Cache Register"},
    {"mcr p15 0 <Rd> c7 c5 1", "Invalidate Instruction Cache Line (using MVA) Register"},
    {"mcr p15 0 <Rd> c7 c5 2", "Invalidate Instruction Cache Line (using Index) Register"},
    {"mcr p15 0 <Rd> c7 c5 4", "Flush Prefetch Buffer Register"},
    {"mcr p15 0 <Rd> c7 c5 6", "Flush Entire Branch Target Cache Register"},
    {"mcr p15 0 <Rd> c7 c5 7", "Flush Branch Target Cache Entry Register"},
    {"mcr p15 0 <Rd> c7 c6 0", "Invalidate Entire Data Cache Register"},
    {"mcr p15 0 <Rd> c7 c6 1", "Invalidate Data Cache Line (using MVA) Register"},
    {"mcr p15 0 <Rd> c7 c6 2", "Invalidate Data Cache Line (using Index) Register"},
    {"mcr p15 0 <Rd> c7 c7 0", "Invalidate Both Caches Register"},
    {"mcr p15 0 <Rn> c7 c8 0", "VA to PA with privileged read permission check Register"},
    {"mcr p15 0 <Rn> c7 c8 1", "VA to PA with privileged write permission check Register"},
    {"mcr p15 0 <Rn> c7 c8 2", "VA to PA with user read permission check Register"},
    {"mcr p15 0 <Rn> c7 c8 3", "VA to PA with user write permission check Register"},
    {"mcr p15 0 <Rd> c7 c10 0", "Clean Entire Data Cache Register"},
    {"mcr p15 0 <Rd> c7 c10 1", "Clean Data Cache Line (using MVA) Register"},
    {"mcr p15 0 <Rd> c7 c10 2", "Clean Data Cache Line (using Index) Register"},
    {"mcr p15 0 <Rd> c7 c10 4", "Drain Synchronization Barrier Register"},
    {"mcr p15 0 <Rd> c7 c10 5", "Data Memory Barrier Register"},
    {"mcr p15 0 <Rd> c7 c14 0", "Clean and Invalidate Entire Data Cache Register"},
    {"mcr p15 0 <Rd> c7 c14 1", "Clean and Invalidate Data Cache Line (using MVA) Register"},
    {"mcr p15 0 <Rd> c7 c14 2", "Clean and Invalidate Data Cache Line (using Index) Register"},

    {"mcr p15,0 <Rd> c8 C5 0", "Invalidate Instruction TLB Register"},
    {"mcr p15,0 <Rd> c8 C5 1", "Invalidate Instruction TLB Single Entry Register"},
    {"mcr p15,0 <Rd> c8 C5 2", "Invalidate Instruction TLB Entry on ASID match Register"},
    {"mcr p15,0 <Rd> c8 C5 3", "Invalidate Instruction TLB Single Entry on MVA only Register"},
    {"mcr p15,0 <Rd> c8 C6 0", "Invalidate Data TLB Register"},
    {"mcr p15,0 <Rd> c8 C6 1", "Invalidate Data TLB Single Entry Register"},
    {"mcr p15,0 <Rd> c8 C6 2", "Invalidate Data TLB Entry on ASID match Register"},
    {"mcr p15,0 <Rd> c8 C6 3", "Invalidate Data TLB Single Entry on MVA only Register"},
    {"mcr p15,0 <Rd> c8 C7 0", "Invalidate Unified TLB Register"},
    {"mcr p15,0 <Rd> c8 C7 1", "Invalidate Unified TLB Single Entry Register"},
    {"mcr p15,0 <Rd> c8 C7 2", "Invalidate Unified TLB Entry on ASID match Register"},
    {"mcr p15,0 <Rd> c8 C7 3", "Invalidate Unified TLB Single Entry on MVA only Register"},

    {"mrc p15 0 <Rd> c9 c0 0", "Read Data Cache Lockdown Register"},
    {"mcr p15 0 <Rd> c9 c0 0", "Write Data Cache Lockdown Register"},

    {"mrc p15 0 <Rd> c10 c0 0", "Read TLB Lockdown Register"},
    {"mcr p15 0 <Rd> c10 c0 0", "Write TLB Lockdown Register"},
    {"mrc p15 0 <Rd> c10 c2 0", "Read Primary Remap Register"},
    {"mcr p15 0 <Rd> c10 c2 0", "Write Primary Remap Register"},
    {"mrc p15 0 <Rd> c10 c2 1", "Read Normal Remap Register"},
    {"mcr p15 0 <Rd> c10 c2 1", "Write Normal Remap Register"},

    {"mrc p15 0 <Rd> c13 c0 0", "Read Process ID Register"},
    {"mcr p15 0 <Rd> c13 c0 0", "Write Process ID Register"},
    {"mrc p15 0 <Rd> c13 c0 1", "Read Context ID Register"},
    {"mcr p15 0 <Rd> c13 c0 1", "Write Context ID Register"},
    {"mrc p15 0 <Rd> c13 c0 2", "Read Thread ID User and Privileged Read Write Register"},
    {"mcr p15 0 <Rd> c13 c0 2", "Write Thread ID User and Privileged Read Write Register"},
    {"mrc p15 0 <Rd> c13 c0 3", "Read Thread ID User Read only Register"},
    {"mcr p15 0 <Rd> c13 c0 3", "Write Thread ID User Read only Register"},
    {"mrc p15 0 <Rd> c13 c0 4", "Read Thread ID Privileged Read Write only Register"},
    {"mcr p15 0 <Rd> c13 c0 4", "Write Thread ID Privileged Read Write only Register"},

    {"mrc p15 0 <Rd> c15 c12 0", "Read Performance Monitor Control Register"},
    {"mcr p15 0 <Rd> c15 c12 0", "Write Performance Monitor Control Register"},
    {"mrc p15 0 <Rd> c15 c12 1", "Read Cycle Counter Register"},
    {"mcr p15 0 <Rd> c15 c12 1", "Write Cycle Counter Register"},
    {"mrc p15 0 <Rd> c15 c12 2", "Read Count Register 0"},
    {"mcr p15 0 <Rd> c15 c12 2", "Write Count Register 0"},
    {"mrc p15 0 <Rd> c15 c12 3", "Read Count Register 1"},
    {"mcr p15 0 <Rd> c15 c12 3", "Write Count Register 1"},

    {"mcr p15 5 <Rd> c15 c4 2", "Read Main TLB Entry Register"},
    {"mcr p15 5 <Rd> c15 c4 4", "Write Main TLB Entry Register"},
    {"mrc p15 5 <Rd> c15 c5 2", "Read Main TLB VA Register"},
    {"mcr p15 5 <Rd> c15 c5 2", "Write Main TLB VA Register"},
    {"mrc p15 5 <Rd> c15 c6 2", "Read Main TLB PA Register"},
    {"mcr p15 5 <Rd> c15 c6 2", "Write Main TLB PA Register"},
    {"mrc p15 5 <Rd> c15 c7 2", "Read Main TLB Attribute Register"},
    {"mcr p15 5 <Rd> c15 c7 2", "Write Main TLB Attribute Register"},

    {"mrc p15 7 <Rd> c15 c1 0", "Read TLB Debug Control Register"},
    {"mcr p15 7 <Rd> c15 c1 0", "Write TLB Debug Control Register"}
};
